"""CDMP K-sweep runner.

Trains and evaluates CDMP for each K in a list, then prints a ranked summary.
K=1 is the regression test (should reproduce vanilla AnomalyCLIP).
Centroids for each K must be pre-generated by scripts/cluster_prototypes.py.

Example:
    # First generate centroids for each K
    for K in 1 2 4 6 8; do
        python scripts/cluster_prototypes.py \\
            --data_path ./data/mvtecdataset --dataset mvtec \\
            --K $K --output_dir ./centroids/K${K}_mvtec
    done

    # Then sweep
    python cdmp/run_sweep.py \\
        --K_list 1 2 4 6 8 \\
        --train_data_path ./data/mvtecdataset --train_dataset mvtec \\
        --test_data_path  ./data/visa         --test_dataset  visa \\
        --centroid_root   ./centroids \\
        --centroid_suffix _mvtec
"""

import os
import sys
import json
import argparse
import subprocess

import numpy as np
from tabulate import tabulate

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))


def centroid_path_for_K(args, K):
    if K == 1:
        return ""   # K=1 needs no centroids
    return os.path.join(
        args.centroid_root,
        f"K{K}{args.centroid_suffix}",
        "cluster_centroids.pt",
    )


def metrics_path(args, K):
    return os.path.join(args.results_root, f"K{K}", "metrics.json")


def ckpt_path(args, K):
    return os.path.join(args.ckpt_root, f"K{K}", f"epoch_{args.epoch}.pth")


def load_metrics(path):
    try:
        with open(path) as f:
            d = json.load(f)
        if d.get("mean") is not None:
            return d
    except (OSError, json.JSONDecodeError):
        pass
    return None


def run(cmd, env):
    print("\n>>> " + " ".join(str(c) for c in cmd), flush=True)
    subprocess.run([str(c) for c in cmd], env=env, check=True)


def train_one(args, K, env):
    ckpt_dir = os.path.join(args.ckpt_root, f"K{K}")
    os.makedirs(ckpt_dir, exist_ok=True)
    cmd = [
        args.python, os.path.join(os.path.dirname(__file__), "train.py"),
        "--dataset",       args.train_dataset,
        "--train_data_path", args.train_data_path,
        "--save_path",     ckpt_dir,
        "--features_list", *[str(x) for x in args.features_list],
        "--image_size",    args.image_size,
        "--batch_size",    args.batch_size,
        "--epoch",         args.epoch,
        "--save_freq",     args.epoch,        # only save final checkpoint
        "--print_freq",    args.print_freq,
        "--depth",  args.depth,
        "--n_ctx",  args.n_ctx,
        "--t_n_ctx", args.t_n_ctx,
        "--cdmp_K", K,
        "--cluster_weight",   args.cluster_weight,
        "--repulsion_weight", args.repulsion_weight,
        "--repulsion_margin", args.repulsion_margin,
    ]
    cp = centroid_path_for_K(args, K)
    if cp:
        cmd += ["--centroid_path", cp]
    run(cmd, env)


def test_one(args, K, env):
    save_dir = os.path.join(args.results_root, f"K{K}")
    os.makedirs(save_dir, exist_ok=True)
    m_path = metrics_path(args, K)
    cmd = [
        args.python, os.path.join(os.path.dirname(__file__), "test.py"),
        "--dataset",         args.test_dataset,
        "--data_path",       args.test_data_path,
        "--save_path",       save_dir,
        "--checkpoint_path", ckpt_path(args, K),
        "--features_list",   *[str(x) for x in args.features_list],
        "--image_size",      args.image_size,
        "--depth",    args.depth,
        "--n_ctx",    args.n_ctx,
        "--t_n_ctx",  args.t_n_ctx,
        "--metrics",  "image-pixel-level",
        "--cdmp_K",   K,
        "--metrics_out", m_path,
    ]
    run(cmd, env)


def summarize(args):
    rows = []
    for K in args.K_list:
        d = load_metrics(metrics_path(args, K))
        if d is None:
            rows.append([K, "-", "-", "-", "-", "-"])
        else:
            rows.append([K, d["pixel_auroc"], d["pixel_aupro"],
                         d["image_auroc"], d["image_ap"], d["mean"]])

    rows.sort(key=lambda r: (r[5] if isinstance(r[5], (int, float)) else -1), reverse=True)
    headers = ["K", "pixel_auroc", "pixel_aupro", "image_auroc", "image_ap", "MEAN"]
    table = tabulate(rows, headers=headers, tablefmt="pipe")
    print("\n===== CDMP K-SWEEP SUMMARY =====")
    print(table)

    done = [r for r in rows if isinstance(r[5], (int, float))]
    best_line = ""
    if done:
        best = done[0]
        best_line = f"\nBest: K={best[0]}  MEAN={best[5]}"
        print(best_line)

    os.makedirs(args.results_root, exist_ok=True)
    with open(os.path.join(args.results_root, "summary.md"), "w") as f:
        f.write("# CDMP K-sweep summary\n\n" + table + "\n" + best_line + "\n")
    print(f"\nSaved → {os.path.join(args.results_root, 'summary.md')}")


def main():
    parser = argparse.ArgumentParser("CDMP K sweep")

    parser.add_argument("--K_list", type=int, nargs="+", default=[1, 2, 4, 6, 8])
    parser.add_argument("--python", type=str, default=sys.executable,
                        help="Python executable for subprocesses (train.py / test.py). "
                             "Useful when run_sweep.py is run from a different env.")

    # data
    parser.add_argument("--train_data_path", type=str, default="./data/mvtecdataset")
    parser.add_argument("--train_dataset",   type=str, default="mvtec")
    parser.add_argument("--test_data_path",  type=str, default="./data/visa")
    parser.add_argument("--test_dataset",    type=str, default="visa")

    # centroids
    parser.add_argument("--centroid_root",   type=str, default="./centroids",
                        help="Directory containing K{K}{suffix}/ subdirs.")
    parser.add_argument("--centroid_suffix", type=str, default="_mvtec",
                        help="Suffix appended to K{K} to form the centroid subdir.")

    # output
    parser.add_argument("--ckpt_root",    type=str, default="./checkpoints/cdmp_sweep")
    parser.add_argument("--results_root", type=str, default="./results/cdmp_sweep")

    # model hyperparams — keep at AnomalyCLIP defaults
    parser.add_argument("--depth",        type=int, default=9)
    parser.add_argument("--n_ctx",        type=int, default=12)
    parser.add_argument("--t_n_ctx",      type=int, default=4)
    parser.add_argument("--features_list",type=int, nargs="+", default=[6, 12, 18, 24])
    parser.add_argument("--image_size",   type=int, default=518)
    parser.add_argument("--batch_size",   type=int, default=8)
    parser.add_argument("--epoch",        type=int, default=15)
    parser.add_argument("--print_freq",   type=int, default=1)

    # CDMP loss weights
    parser.add_argument("--cluster_weight",   type=float, default=1.0)
    parser.add_argument("--repulsion_weight", type=float, default=0.5)
    parser.add_argument("--repulsion_margin", type=float, default=-0.3)

    # control
    parser.add_argument("--summary_only", action="store_true",
                        help="Skip training/testing, only regenerate summary.")
    parser.add_argument("--force",        action="store_true",
                        help="Re-train/test even if metrics already exist.")
    parser.add_argument("--device", type=str, default="0",
                        help="CUDA_VISIBLE_DEVICES")

    args = parser.parse_args()

    env = dict(os.environ)
    env["CUDA_VISIBLE_DEVICES"] = args.device

    if not args.summary_only:
        for K in args.K_list:
            m_path = metrics_path(args, K)
            if not args.force and load_metrics(m_path) is not None:
                print(f"[skip] K={K} already has metrics: {m_path}")
                continue

            print(f"\n{'='*50}")
            print(f"  K = {K}")
            print(f"{'='*50}")

            ck = ckpt_path(args, K)
            if args.force or not os.path.exists(ck):
                train_one(args, K, env)
            else:
                print(f"[skip-train] checkpoint exists: {ck}")

            test_one(args, K, env)

    summarize(args)


if __name__ == "__main__":
    main()
